export const Category = {
  parks: [
    'amusement_park',
    'aquarium',
    'park',
    'campground',
    'tourist_attraction',
    'zoo',
  ],
  restaurants: [
    'bakery',
    'bar',
    'cafe',
    'restaurant',
    'meal_delivery',
    'meal_takeaway',
    'shopping_mall',
  ],
  arts: [
    'art_gallery',
    'movie_theater',
    'museum',
    'church',
    'city_hall',
    'library',
    'hindu_temple',
    'mosque',
    'synagogue',
  ],
  others: [
    'atm',
    'bank',
    'beauty_salon',
    'book_store',
    'bowling_alley',
    'casino',
    'florist',
    'night_club',
    'spa',
    'stadium',
  ],
} as const;
